<%@ Page Language="VB" AutoEventWireup="false" CodeFile="form-comesse-conf.aspx.vb" Inherits="form_comesse_conf" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Confezione - Comesse</title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../../css/bootstrap.min.css" />
    <link rel="stylesheet" href="../../css/matrix-style.css" />
    <link rel="stylesheet" href="../../css/matrix-media.css" />
    <link rel="stylesheet" href="../../css/font-awesome.min.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'/>
    <script src="../../js/jquery-1.12.4.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet"/>
    <style>
        *:not(.icon-th):not(.icon) {
            font-family: 'Exo', sans-serif!important;
        }
        .header-fixed{
            position:fixed;
        }
            .results tr[visible='false'],
            .no-result{
              display:none;
            }
            .results tr[visible='true']{
              display:table-row;
            }      
                   body{
            height:750px;
        }
    </style>

</head>
<body>
   <form action="#"  class="form-horizontal" runat="server">
      <asp:ScriptManager runat="server"></asp:ScriptManager>
      <asp:UpdatePanel runat="server">
          <ContentTemplate>

            <div id="content">
            <div id="content-header">
              <div id="breadcrumb"> <a href="dashboard.aspx" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#" class="tip-bottom">Production Managment</a> <a href="#" class="current">Article</a> </div>
              <h1>Comesse view - Confezione</h1>
            </div>
            <div class="container-fluid">
              <hr/>
              <div class="row-fluid">

                <div class="span11">
                    <div class="widget-box">
                      <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
                        <h5>Active Commesse in production</h5>
                        <input type="text" class="search form-control" placeholder="Search:">
                      </div>
                   
                    <div class="widget-content" style="height: 65vh; overflow: auto">
            
                          <asp:gridview
                              runat="server" 
                              CssClass="table table-bordered data-table results" 
                              datasourceid="CustomersSqlDataSourceArticle" 
                              autogeneratecolumns="true" 
                              autogenerateeditbutton="false" 
                              AutoGenerateDeleteButton="false" 
                              allowpaging="false"
                              AllowSorting="true" 

                              id="ConfA_Grid">
                          </asp:gridview>

                          <asp:sqldatasource id="CustomersSqlDataSourceArticle"  
                            Selectcommand="  SELECT Articol,NrComanda,DataLansare,DataLivrare,Cantitate, Descriere,Stagione,Client,Comenzi.IdSector, IdClient,IdArticol FROM Comenzi
INNER JOIN Articole ON Comenzi.IdArticol = Articole.Id
INNER JOIN Clienti ON Comenzi.IdClient = Clienti.Id WHERE Comenzi.IdSector='1'"
                            Connectionstring="<%$ ConnectionStrings:DefaultConnection%>"
                            runat="server">
                          </asp:sqldatasource>
                      </div> 
                    </div>
                </div>
              </div>
            </div>

        </ContentTemplate>
      </asp:UpdatePanel>
    </form>

                        <%-- SEARCH --%>
            <script>

                        Sys.Application.add_load(initSomething);
                        function initSomething() {

                            $(".search").keyup(function () {
                                var searchTerm = $(".search").val();
                                var listItem = $('.results tbody').children('tr');
                                var searchSplit = searchTerm.replace(/ /g, "'):containsi('");

                                $.extend($.expr[':'], {
                                    'containsi': function (elem, i, match, array) {
                                        return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
                                    }
                                });

                                $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function (e) {
                                    $(this).attr('visible', 'false');
                                });

                                $(".results tbody tr:containsi('" + searchSplit + "')").each(function (e) {
                                    $(this).attr('visible', 'true');
                                });

                            });

                        }
                </script>

</body>
</html>