<%@ Page Language="VB" AutoEventWireup="false" CodeFile="form-exacta.aspx.vb" Inherits="form_exacta" %>


<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Faze</title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../../css/bootstrap.min.css" />
    <link rel="stylesheet" href="../../css/matrix-style.css" />
    <link rel="stylesheet" href="../../css/matrix-media.css" />
    <link rel="stylesheet" href="../../css/font-awesome.min.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'/>
    <script src="../../js/jquery-1.12.4.min.js"></script>

        <link rel="stylesheet" href="../../css/font-awesome.min.css" />

    <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet"/>
    <style>
        *:not(.icon-th):not(.icon) {
            font-family: 'Exo', sans-serif!important;
        }
        .header-fixed{
            position:fixed;
        }

            .results tr[visible='false'],.no-result{
              display:none;
            }

            .results tr[visible='true']{
              display:table-row;
            }

 
            .exacta_header{
                font-size:18pt;
            }
                   body{
            height:750px;
        }
      
    </style>

</head>
<body>
   

   <form action="#" method="get" class="form-horizontal" runat="server">
      <asp:ScriptManager runat="server"></asp:ScriptManager>
      <asp:UpdatePanel runat="server">
          <ContentTemplate>
              <br /><br />
             

            <div id="content">
            <div id="content-header">
                <br />
              <h1>Exacta Machines - Log's</h1>
            </div>
            <div class="container-fluid">
              <div class="row-fluid">
                 

                <div class="span11">
                    <div class="widget-box">
                      <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
                        <h5>List of Logs</h5>
                        <input type="text" class="search form-control" placeholder="Search:">
                      </div>
                   
                    <div class="widget-content" style="height: 100%; overflow: auto">
            
                          <asp:gridview
                              runat="server" 
                              CssClass="table table-bordered data-table results" 
                              datasourceid="CustomersSqlDataSourceArticle" 
                              autogeneratecolumns="true" 
                              autogenerateeditbutton="false" 
                              AutoGenerateDeleteButton="false"                             
                              allowpaging="false"
                              AllowSorting="true"                               
                              datakeynames="Id" 
                              OnRowDataBound="ConfA_Grid_DataBound"                 
                              id="ConfA_Grid"
                              HeaderStyle-CssClass="exacta_header">
                          </asp:gridview>

                        <asp:sqldatasource id="CustomersSqlDataSourceArticle"  
                        Selectcommand="Select * From [Log]"
                        connectionstring="<%$ConnectionStrings:ExactaConnection%>"
                        runat="server">
                        </asp:sqldatasource>
                      </div> 
                    </div>
                </div>
            
            </div>
 
        </ContentTemplate>
      </asp:UpdatePanel>
    </form>

                       <%-- SEARCH --%>
                <script>

                        Sys.Application.add_load(initSomething);
                        function initSomething() {

                            $(".search").keyup(function () {
                                var searchTerm = $(".search").val();
                                var listItem = $('.results tbody').children('tr');
                                var searchSplit = searchTerm.replace(/ /g, "'):containsi('");

                                $.extend($.expr[':'], {
                                    'containsi': function (elem, i, match, array) {
                                        return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
                                    }
                                });

                                $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function (e) {
                                    $(this).attr('visible', 'false');
                                });

                                $(".results tbody tr:containsi('" + searchSplit + "')").each(function (e) {
                                    $(this).attr('visible', 'true');
                                });

                            });

                        }

                </script>


<%--<script src="./js/jquery-1.12.4.min.js"></script>--%>


</body>
</html>