<%@ Page Language="VB" AutoEventWireup="false" CodeFile="form-faze-stiro.aspx.vb" Inherits="form_faze_stiro" %>

<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Faze</title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../../css/bootstrap.min.css" />
    <link rel="stylesheet" href="../../css/matrix-style.css" />
    <link rel="stylesheet" href="../../css/matrix-media.css" />
    <link rel="stylesheet" href="../../css/font-awesome.min.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'/>
    <script src="../../js/jquery-1.12.4.min.js"></script>

      <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet"/>
    <style>
        *:not(.icon-th):not(.icon) {
            font-family: 'Exo', sans-serif!important;
        }
        .header-fixed{
            position:fixed;
        }

            .results tr[visible='false'],.no-result{
              display:none;
            }

            .results tr[visible='true']{
              display:table-row;
            }

                   body{
            height:750px;
        }
      
    </style>

</head>
<body>
   

   <form action="#" method="get" class="form-horizontal" runat="server">
      <asp:ScriptManager runat="server"></asp:ScriptManager>
      <asp:UpdatePanel runat="server">
          <ContentTemplate>

            <div id="content">
            <div id="content-header">
            <br /><br />
              <h1>Faze managment system</h1>
                <%--<hr/>--%>

            </div>
                
            <div class="container-fluid">
              <div class="row-fluid">
<%--                  <div class="span3">
                      <div class="widget-box">
                          <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                              <h5>Add New Faze</h5>
                          </div>

                          <div class="widget-content nopadding">
                              <label class="control-label col-xs-4">Code:</label>
                              <div class="controls">
                                  <asp:TextBox runat="server" ID="txt_code" CssClass="col-xs-8" ></asp:TextBox>
                              </div>
                              <br />

                              <div class="widget-content nopadding">
                                  <label class="control-label col-xs-4">Operatie:</label>
                                  <div class="controls">
                                      <asp:TextBox runat="server" ID="txt_operatie" CssClass="col-xs-8" ></asp:TextBox>
                                      <br />
                                      <asp:Label runat="server" ID="lbl_status"></asp:Label>
                                  </div>
                                         
                                  <br />

           
                                  <div class="form-actions ">
                                      <asp:button type="submit" runat="server" ID="btn_adduser" class="btn btn-success col-xs-12" Text="Add Faze"></asp:button>
                      
                                  </div>
          
                              </div>
                          </div>

                      </div>
                      <br />

                  </div>--%>
                <div class="span11">
                    <div class="widget-box">
                      <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
                        <h5>List of Faze</h5>
                        <input type="text" class="search form-control" placeholder="Search:">
                      </div>
                   
                    <div class="widget-content" style="height: 65vh; overflow: auto">
            
                          <asp:gridview
                              runat="server" 
                              CssClass="table table-bordered data-table results" 
                              datasourceid="CustomersSqlDataSourceArticle" 
                              autogeneratecolumns="true" 
                              autogenerateeditbutton="false" 
                              AutoGenerateDeleteButton="false" 
                              allowpaging="false"
                              AllowSorting="true" 
                              datakeynames="Id" 
                              OnRowDataBound="ConfA_Grid_DataBound"
                              OnRowUpdating="TaskGridView_RowUpdating"
                              OnRowDeleting="TaskGridView_RowDeleteing"
                              id="ConfA_Grid">
                          </asp:gridview>

                        <asp:sqldatasource id="CustomersSqlDataSourceArticle"  
                        Selectcommand="Select [Id], [CodOperatie], [Operatie] , [IdSector] From [Operatii] Where IdSector=2 ORDER BY [CodOperatie] DESC"
                        Updatecommand="Update Operatii SET CodOperatie=@CodOperatie, Operatie=@Operatie, IdSector=@IdSector WHERE (Id = @Id)"
                        DeleteCommand="DELETE FROM [Operatii] WHERE Id = @Id"
                        connectionstring="<%$ ConnectionStrings:DefaultConnection%>"
                        runat="server">
                        </asp:sqldatasource>
                      </div> 
                    </div>
                </div>
            
            </div>
 
        </ContentTemplate>
      </asp:UpdatePanel>
    </form>

                       <%-- SEARCH --%>
                <script>

                        Sys.Application.add_load(initSomething);
                        function initSomething() {

                            $(".search").keyup(function () {
                                var searchTerm = $(".search").val();
                                var listItem = $('.results tbody').children('tr');
                                var searchSplit = searchTerm.replace(/ /g, "'):containsi('");

                                $.extend($.expr[':'], {
                                    'containsi': function (elem, i, match, array) {
                                        return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
                                    }
                                });

                                $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function (e) {
                                    $(this).attr('visible', 'false');
                                });

                                $(".results tbody tr:containsi('" + searchSplit + "')").each(function (e) {
                                    $(this).attr('visible', 'true');
                                });

                            });

                        }

                </script>


<%--<script src="./js/jquery-1.12.4.min.js"></script>--%>


</body>
</html>
